// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "我的 App",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "我的 App",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .boat),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/tid-kijyun/Kanna", "5.2.7"..<"6.0.0"),
        .package(url: "https://github.com/Alamofire/Alamofire", "5.6.4"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Kanna", package: "Kanna"),
                .product(name: "Alamofire", package: "Alamofire")
            ],
            path: "."
        )
    ]
)
